---
title: "Assinment 03"
author: "Forouh"
date: "2019/10/01"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(gapminder) 
library(rmarkdown)
library(tibble)
library(DT)
library(tidyverse)
library(tsibble)
library(scales)
library(dplyr)
library(ggplot2)
library(scales)
```


#(Task Option 2)The maximum and minimum of GDP per capita for all continents.

```{r, echo=TRUE}

#The table below show maximum and minimun of gdpPercap for all continents.

gapminder %>% 
group_by(continent) %>% 
summarize(maxgdp = max(gdpPercap),mingdp= min(gdpPercap))
```


```{r, echo=TRUE}

# using this box plot we can show the minimum and maximum of gdppercap for each continent. 

gapminder %>%
ggplot(aes(continent, gdpPercap)) +
geom_boxplot(size = 1.5) +
scale_y_log10(labels = scales::dollar_format()) +
labs(title = "GDP per Capita per Continent", x = "Continent", y = "GDP per Capita")
```


#(Task Option 3)Look at the spread of GDP per capita within the continents.

```{r, echo=TRUE}

# using Geom_density_ridges plot we can visualize the spread of gdpPercap between continents. Based on this plot we can say Ocenia and Europe have more variability of gdpPercapita between their countries. In contrast Asia, Africa and Americas show a narrow spread.

gapminder %>% 
  ggplot(aes(gdpPercap, continent, fill = continent)) + 
  scale_x_log10(label = scales::comma_format()) + 
  ggridges::geom_density_ridges() + 
  xlab("Log10(gdpPerCap)") 
```


#(Task Option 5)How is life expectancy changing over time on different continents?

```{r, echo=TRUE}
# 1: By using separate plot for each continent. Based on these plots except for some countries in Africa and a few countries in Asia and Americas with some fluctuations, life expectancy has increased for most countries over the years.

gapminder %>%
ggplot(aes(year, lifeExp, group = country, colour = continent)) +
  geom_line(alpha = 0.5) +
  scale_x_log10( labels = scales::comma_format())+
  facet_wrap(~ continent)
```
```{r, echo=TRUE}

# 2: By calculating the average of life expectancy for each continent and showing in one plot. 

gapminder %>% 
  group_by(continent, year) %>%
  summarise(mean_lifeExp = mean(lifeExp)) %>%
  ggplot(aes(year, mean_lifeExp, color = continent)) +
  geom_line(alpha = 1) +
  ylab("mean Life Expectancy")
```

